import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Explicit sidebar structure for Urdu
  tutorialSidebar: [
    'intro',
    '01-introduction-to-physical-ai',
    '02-foundations-of-robotics',
    '03-human-inspired-design-principles',
    '04-perception-systems',
    '05-ai-deep-learning-and-control',
    '06-locomotion-and-manipulation',
    'urdu-translation',
  ],
};

export default sidebars;